ARG VER=3.12

FROM python:${VER}-alpine
RUN apk add make git uv nodejs

WORKDIR /app
COPY pyproject.toml readme.md uv.lock /app/
RUN uv sync --frozen
COPY . /app

CMD ["sh", "-c", "make check && make test"]
